services:
  relay:
    container_name: haven-relay
    image: holgerhatgarkeinenode/haven-docker:v1.0.3
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./templates:/app/templates"
      - "./blossom:/app/blossom"
      - "./relays_import.json:/app/relays_import.json"
      - "./relays_blastr.json:/app/relays_blastr.json"
    ports:
      - "3355:${RELAY_PORT:-3355}"
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    restart: unless-stopped

  tor:
    image: lncm/tor:0.4.7.9@sha256:86c2fe9d9099e6376798979110b8b9a3ee5d8adec27289ac4a5ee892514ffe92
    container_name: haven-tor
    volumes:
      - ./tor/torrc:/etc/tor/torrc
      - ./tor/data:/var/lib/tor
    restart: on-failure
    stop_grace_period: 10m30s
    depends_on:
      - relay
