name: Docker Image CI

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          docker build --build-arg VERSION=$VERSION -t holgerhatgarkeinenode/haven-docker:$VERSION .

      - name: Push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker push holgerhatgarkeinenode/haven-docker:$VERSION
